-- Vice City Forums operations observability foundation.
--
-- Purpose:
-- 1. Keep an auditable rolling record of published creative so the mandatory
--    seven-day exact/near-duplicate check is enforceable.
-- 2. Record daily forum activity separately from seeded/staff activity so
--    operations checks can distinguish genuine member participation.
--
-- This migration is intentionally append-oriented and admin/service-role only.
-- No anon/authenticated read policies are created here.

create table if not exists public.vcf_publication_ledger (
  id uuid primary key default gen_random_uuid(),
  published_at timestamptz not null,
  channel text not null,
  platform text not null,
  campaign text,
  content_type text not null default 'image'
    check (content_type in ('image','video','carousel','text','story','reel','short')),
  public_url text,
  asset_url text,
  asset_sha256 text,
  visual_fingerprint text,
  near_duplicate_of uuid references public.vcf_publication_ledger(id) on delete set null,
  subject_signature text,
  composition_signature text,
  diversity_tags jsonb not null default '{}'::jsonb,
  watermark_present boolean,
  no_children_verified boolean,
  selfie_pov_verified boolean,
  hud_present boolean,
  aftermath_visible boolean,
  ai_generated boolean not null default false,
  ai_disclosure_present boolean,
  provenance_label text,
  compliance_status text not null default 'pending'
    check (compliance_status in ('pending','pass','fail','approved_exception')),
  compliance_notes text,
  approved_by text,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists uq_vcf_publication_public_url
  on public.vcf_publication_ledger(public_url)
  where public_url is not null;

create index if not exists idx_vcf_publication_channel_published
  on public.vcf_publication_ledger(channel, published_at desc);

create index if not exists idx_vcf_publication_sha256
  on public.vcf_publication_ledger(asset_sha256)
  where asset_sha256 is not null;

create index if not exists idx_vcf_publication_visual_fingerprint
  on public.vcf_publication_ledger(visual_fingerprint)
  where visual_fingerprint is not null;

alter table public.vcf_publication_ledger enable row level security;

comment on table public.vcf_publication_ledger is
  'VCF published-media ledger used for seven-day duplicate, safety, branding and provenance checks.';

create table if not exists public.vcf_forum_activity_events (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  event_type text not null
    check (event_type in ('signup','profile_completed','thread_created','reply_created','reaction_created','login','return_visit')),
  actor_id uuid,
  actor_kind text not null default 'member'
    check (actor_kind in ('member','staff','seed','system')),
  thread_id uuid,
  category_id uuid,
  acquisition_source text,
  acquisition_campaign text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_vcf_activity_occurred
  on public.vcf_forum_activity_events(occurred_at desc);

create index if not exists idx_vcf_activity_type_occurred
  on public.vcf_forum_activity_events(event_type, occurred_at desc);

create index if not exists idx_vcf_activity_actor_occurred
  on public.vcf_forum_activity_events(actor_id, occurred_at desc)
  where actor_id is not null;

alter table public.vcf_forum_activity_events enable row level security;

comment on table public.vcf_forum_activity_events is
  'Operational activity ledger. actor_kind keeps seeded/staff activity distinct from genuine member activity.';

create table if not exists public.vcf_daily_metrics (
  metric_date date primary key,
  new_signups integer not null default 0 check (new_signups >= 0),
  completed_profiles integer not null default 0 check (completed_profiles >= 0),
  genuine_threads integer not null default 0 check (genuine_threads >= 0),
  seeded_threads integer not null default 0 check (seeded_threads >= 0),
  genuine_replies integer not null default 0 check (genuine_replies >= 0),
  staff_replies integer not null default 0 check (staff_replies >= 0),
  active_members integer not null default 0 check (active_members >= 0),
  returning_members integer not null default 0 check (returning_members >= 0),
  referral_visits integer not null default 0 check (referral_visits >= 0),
  top_acquisition_source text,
  notes text,
  captured_at timestamptz not null default now()
);

alter table public.vcf_daily_metrics enable row level security;

comment on table public.vcf_daily_metrics is
  'Daily VCF operating metrics. Genuine activity is intentionally separated from seeded/staff activity.';

-- Service/admin query used by the daily operations check.
create or replace view public.vcf_publication_last_7_days as
select *
from public.vcf_publication_ledger
where published_at >= now() - interval '7 days';
