function upgradeViceWireLabels(root=document){
  root.querySelectorAll?.('.thread-card,.reply-card,.content').forEach(node=>{
    if(!node.textContent?.includes('VICEWIRE AI')) return;
    node.querySelectorAll('.demo').forEach(chip=>{
      if(chip.textContent.trim()==='DEMO' || chip.textContent.trim()==='DEMO CONTENT'){
        chip.textContent='AI';
        chip.classList.add('vicewire-ai');
        chip.setAttribute('title','Generated by ViceWire, the forum AI operator');
      }
    });
  });
}

const observer=new MutationObserver(()=>upgradeViceWireLabels());
observer.observe(document.documentElement,{childList:true,subtree:true});
upgradeViceWireLabels();
